Repository ucsb-cs156-s22/s22-4pm-happycows, pull requests merged in 2022-06, with the labels that each got.

#45 s22-4pm-4: Vr backend degradation rate field added
  src/main/java/edu/ucsb/cs156/happiercows/advice/HappierCowsControllerAdvice.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: s22-4pm-4, :gear: :interrobang: Deploying on QA

#48 s22-4pm-3 - Added leaderboardFixtures file with 3 boards and 1 board formats
  frontend/src/fixtures/leaderboardFixtures.js
Labels: s22-4pm-3

#70 s22-4pm-3 cd - Footer Link Updated
  frontend/src/main/components/Nav/Footer.js
Labels: s22-4pm-3

#73 s22-4pm-3 cd - Replaced React Logo with Cow Drawing
  frontend/public/favicon.ico
  frontend/public/logo192.png
  frontend/public/logo512.png
Labels: s22-4pm-3

#78 s22-4pm-3 cd - Site Name Updated
  frontend/public/index.html
Labels: s22-4pm-3

#80 4pm-4: RobinW - Resolved the play page bad user commons api requests issue
  frontend/src/main/pages/PlayPage.js
Labels: bug, s22-4pm-4, s22-4pm-3

#50 s22-4pm-4: Zoey show leaderboard with common id Frontend
  frontend/src/App.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/pages/AdminShowLeaderboardPage.js
  frontend/src/tests/pages/AdminListCommonsPage.test.js
  frontend/src/tests/pages/AdminShowLeaderboard.test.js
Labels: s22-4pm-4, :+1: Merge Candidate

#59 4pm-4: RobinW - toast issue when updating and deleting commons
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/main/utils/commonsUtils.js
  frontend/src/tests/pages/AdminListCommonsPage.test.js
  frontend/src/tests/utils/commonsUtil.test.js
Labels: s22-4pm-4, 10

#54 s22-4pm-4: hn & ap Add checkbox for the showLeaderboard field
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/pages/AdminCreateCommonsPage.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
Labels: s22-4pm-4

#63 4pm-4: RobinW - corrected start date initialization in edit page
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
Labels: s22-4pm-4, 5

#46 s22-4pm-4: robin degradation rate frontend
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/pages/AdminCreateCommonsPage.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
Labels: s22-4pm-4, :gear: :interrobang: Deploying on QA

#89 s22-4pm-3 sw - Created an API call in commons controller to get all UserCommons based on Id to be used for the Leaderboard
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/UserCommonsRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: s22-4pm-3, 20

#44 s22-4pm-3 cs - Added React Component for Leaderboard, Leaderboard Table, LeaderboardPage, and all tests
  frontend/src/App.js
  frontend/src/fixtures/leaderboardFixtures.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
  frontend/src/main/pages/LeaderboardPage.js
  frontend/src/stories/components/Leaderboard/LeaderboardTable.stories.js
  frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
  frontend/src/tests/pages/LeaderboardPage.test.js
Labels: s22-4pm-3

#88 s22-4pm-3 cd - Update .gitignore to ignore .DS_Store OS generated file
  .gitignore
Labels: SETUP, s22-4pm-3
