Repository ucsb-cs156-s22/s22-4pm-happycows, pull requests merged in 2022-05, with the labels that each got.

#10 4pm 4: rw qa setup
  README.md
Labels: SETUP, 4pm-4, 5

#7 4Pm-4: Update README.md with Heroku Production links
  README.md
Labels: SETUP, s22-4pm-4, Merge Candidate

#33 Update README.md
  README.md
Labels: SETUP, 5, s22-4pm-3, Merge Candidate

#8 Update README.md - Added CodeCov
  README.md
Labels: SETUP, s22-4pm-3, Merge Candidate

#29 Vr - s22-4pm-4 pull from starter
  pom.xml
  src/main/java/edu/ucsb/cs156/happiercows/HappierCowsApplication.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/jobs/Job.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/jobs/JobsRepository.java
  src/main/java/edu/ucsb/cs156/happiercows/services/jobs/JobContext.java
  src/main/java/edu/ucsb/cs156/happiercows/services/jobs/JobContextConsumer.java
  src/main/java/edu/ucsb/cs156/happiercows/services/jobs/JobService.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CSRFControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/JobsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/ProfitsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/SystemInfoControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserInfoControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UsersControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/entities/UserTests.java
Labels: SETUP, s22-4pm-4, :+1: Merge Candidate

#28 Staff PC: Pull in code to run async jobs, and address backend testing tech debt
  .env.SAMPLE
  docs/oauth.md
  pom.xml
  src/test/java/edu/ucsb/cs156/happiercows/controllers/JobsControllerTests.java
Labels: :+1: Merge Candidate, Staff-pr

#31 s22-4pm-4: hn added showLeaderboard boolean variable to database
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: s22-4pm-4, :+1: Merge Candidate, :+1: PEER cr done
